image: node:lts

stages:
  - init
  - tests
  - build

cache:
  untracked: true

init:
  stage: init
  script:
    - npm ci

tests:
  stage: tests
  cache:
    policy: pull
  script:
    - npm run test-ci
    - npm run e2e-ci

build:
  stage: build
  script:
    - npm run-script build
  artifacts:
    paths:
      - dist/
