image: node:lts

stages:
  - init
  - build

cache:
  untracked: true

init:
  stage: init
  cache:
    paths:
      - node_modules/
  script:
    - npm ci

build:
  stage: build
  script:
    - npm run-script build
  artifacts:
    paths:
      - dist/
