export enum ActualitesFiltresEnum {
  ACTUALITE_EQUIPE_ID = 'ENTITENIV3_ID',
  ACTUALITE_THEME_ID = 'THEME_ID',
  ACTUALITE_TITRE = 'TITRE',
  ACTUALITE_AUTEUR_ID = 'AUTEUR_DERNIERE_MAJ_ID',
  STATUT = 'ACTIF',
}
