export enum OperationsFiltresEnum {
  CONSISTANCE = 'CONSISTANCE',
  OUVRAGE = 'OUVRAGE',
  REF_EXTERNE = 'REF_EXTERNE',
  TYPE_OPERATION = 'TYPE_OPERATION',
  NIVEAU_TENSION_ID = 'NIVEAU_TENSION_ID',
  PRIORITE_ID = 'PRIORITE_ID',
  CONSIGNABILITE_ID = 'CONSIGNABILITE_ID',
  ARBITRE = 'ARBITRE',
}
