import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowLeft,
  faAsterisk,
  faAtom,
  faBan,
  faBars,
  faBell,
  faBook,
  faCalendarAlt,
  faClock,
  faCloud,
  faDatabase,
  faEdit,
  faEye,
  faEyeDropper,
  faEyeSlash,
  faFlag,
  faFolder,
  faHdd,
  faHeart,
  faHome,
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faRoad,
  faSave,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserCircle,
  faUserPlus,
  faWrench,
} from '@fortawesome/free-solid-svg-icons';

export function vendors() {
  // Adds the SVG icon to the library so you can use it in your page
  library.add(faUser);
  library.add(faSort);
  library.add(faSortUp);
  library.add(faSortDown);
  library.add(faSync);
  library.add(faEye);
  library.add(faBan);
  library.add(faTimes);
  library.add(faArrowLeft);
  library.add(faSave);
  library.add(faPlus);
  library.add(faPencilAlt);
  library.add(faBars);
  library.add(faHome);
  library.add(faThList);
  library.add(faUserPlus);
  library.add(faRoad);
  library.add(faTachometerAlt);
  library.add(faHeart);
  library.add(faList);
  library.add(faBell);
  library.add(faTasks);
  library.add(faBook);
  library.add(faHdd);
  library.add(faFlag);
  library.add(faWrench);
  library.add(faClock);
  library.add(faCloud);
  library.add(faSignOutAlt);
  library.add(faSignInAlt);
  library.add(faCalendarAlt);
  library.add(faSearch);
  library.add(faTrashAlt);
  library.add(faAsterisk);
  library.add(faLock);
  library.add(faEyeSlash);
  library.add(faEyeDropper);
  library.add(faFolder);
  library.add(faEdit);
  library.add(faAtom);
  library.add(faDatabase);
  library.add(faUserCircle);
}
